using UnityEngine;
using System.Collections;
using System;
using System.IO.Ports;


public class escopetaAr2 : MonoBehaviour
{

    SerialPort stream;

    public GameObject target; // is the gameobject to

    float acc_normalizer_factor = 0.00025f;
    float gyro_normalizer_factor = 1.0f / 32768.0f;   // 32768 is max value captured during test on imu

    float curr_angle_x = 0;
    float curr_angle_y = 0;
    float curr_angle_z = 0;

    float curr_offset_x = 0;
    float curr_offset_y = 0;
    float curr_offset_z = 0;

    // Increase the speed/influence rotation
    public float factor = 7;


    public bool enableRotation;
    public bool enableTranslation;

    // SELECT YOUR COM PORT AND BAUDRATE
    string port = "COM11";
    int baudrate = 9600;
    int readTimeout = 1;

    void Start()
    {
        // open port. Be shure in unity edit > project settings > player is NET2.0 and not NET2.0Subset
        stream = new SerialPort(port, baudrate);

        stream.Open();

        stream.ReadTimeout = readTimeout;

        /*try
        {
            stream.ReadTimeout = readTimeout;
        }
        catch (System.IO.IOException ioe)
        {
            Debug.Log("IOException: " + ioe.Message);
        }*/

        //stream.Open();
    }

    void Update()
    {
        //string dataString = "null received";

        if (stream.IsOpen)
        {
            try
            {
                string dataString = dataString = stream.ReadLine();
                Debug.Log("RCV_1 : " + dataString);
                //if (!dataString.Equals("NOT OPEN"))
                //{
                // recived string is  like  "accx;accy;accz;gyrox;gyroy;gyroz"
                char splitChar = ';';
                string[] dataRaw = dataString.Split(splitChar);
                /*
                // normalized accelerometer values
                float ax = int.Parse(dataRaw[0]) * acc_normalizer_factor;
                float ay = int.Parse(dataRaw[1]) * acc_normalizer_factor;
                float az = int.Parse(dataRaw[2]) * acc_normalizer_factor;
                */
                // normalized gyrocope values
                float gx = int.Parse(dataRaw[0]) * gyro_normalizer_factor;
                float gy = int.Parse(dataRaw[1]) * gyro_normalizer_factor;
                float gz = int.Parse(dataRaw[2]) * gyro_normalizer_factor;
                /*
                // prevent
                if (Mathf.Abs(ax) - 1 < 0) ax = 0;
                if (Mathf.Abs(ay) - 1 < 0) ay = 0;
                if (Mathf.Abs(az) - 1 < 0) az = 0;


                curr_offset_x += ax;
                curr_offset_y += ay;
                curr_offset_z += 0; // The IMU module have value of z axis of 16600 caused by gravity
                */

                // prevent little noise effect
                if (Mathf.Abs(gx) < 0.025f) gx = 0f;
                if (Mathf.Abs(gy) < 0.025f) gy = 0f;
                if (Mathf.Abs(gz) < 0.025f) gz = 0f;

                curr_angle_x += gx;
                curr_angle_y += gy;
                curr_angle_z += gz;

                if (enableTranslation) target.transform.position = new Vector3(curr_offset_x, curr_offset_z, curr_offset_y);
                if (enableRotation) target.transform.rotation = Quaternion.Euler(curr_angle_x * factor, -curr_angle_z * factor, curr_angle_y * factor);
                //}
            }
            catch (System.IO.IOException ioe)
            {
                Debug.Log("IOException: " + ioe.Message);
            }

        }
        //else
           // dataString = "NOT OPEN";
        //Debug.Log("RCV_ 2: " + dataString);

        
    }

}